Repository 100-hours-a-week/18-team-timeline-fe, pull requests merged in 2025-06, with the labels that each got.

#100 chore: App.tsx의 라우트 초기화
  frontend/src/App.tsx
Labels: chore, refactor

#104 style: 회원 페이지에 Prettier 포맷 적용
  frontend/src/components/form/Input.tsx
  frontend/src/index.css
  frontend/src/pages/PU/PU-001/CheckSection.tsx
  frontend/src/pages/PU/PU-001/SignUpForm.tsx
  frontend/src/pages/PU/PU-001/SignUpLogic.ts
  frontend/src/pages/PU/PU-001/index.tsx
  frontend/src/pages/PU/PU-002-01/FindPasswordForm.tsx
  frontend/src/pages/PU/PU-002-01/index.tsx
  frontend/src/pages/PU/PU-002/LoginForm.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/UserInfoForm.tsx
  frontend/src/pages/PU/PU-003/UserInfoLogic.ts
  frontend/src/pages/PU/PU-003/index.tsx
  frontend/src/pages/PU/auth/KakaoCallback.tsx
  frontend/src/pages/PU/components/layout/Wrapper.tsx
  frontend/src/pages/PU/components/ui/Button.tsx
  frontend/src/pages/PU/components/ui/CheckBox.tsx
  frontend/src/pages/PU/components/ui/StaticField.tsx
  frontend/src/pages/PU/utils/validateLogin.ts
  frontend/src/pages/PU/utils/validateSignUp.ts
  frontend/src/pages/PU/utils/validateUserInfo.ts
Labels: style

#107 feat: 댓글에 username 표시
  frontend/src/pages/PN/PN-003/hooks/useComments.ts
Labels: feat

#112 fix: 카카오 로그인 콜백 처리 실패 해결
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/assets/tamnarna_icon.png
  frontend/src/constants/PU/puMessage.ts
  frontend/src/constants/navigationLink.ts
  frontend/src/constants/url.ts
  frontend/src/main.tsx
  frontend/src/pages/PU/auth/KakaoCallback.tsx
  frontend/src/pages/PU/components/form/EmailInput.tsx
  frontend/src/pages/PU/components/form/PasswordInput.tsx
  frontend/src/pages/PU/components/layout/Wrapper.tsx
  frontend/src/pages/PU/components/ui/Button.tsx
  frontend/src/stores/authStore.ts
  frontend/src/utils/handleToken.ts
Labels: fix

#114 feat: 비밀번호 찾기 페이지 로직 수정 및 하드코딩 상수화 리팩토링
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/assets/tamnarna_icon.png
  frontend/src/constants/PU/findPasswordMessage.ts
  frontend/src/constants/PU/puMessage.ts
  frontend/src/constants/navigationLink.ts
  frontend/src/constants/url.ts
  frontend/src/main.tsx
  frontend/src/pages/PU/PU-002-01/FindPasswordForm.tsx
  frontend/src/pages/PU/PU-002-01/index.tsx
  frontend/src/pages/PU/PU-002-01/useFindPasswordLogic.ts
  frontend/src/pages/PU/auth/KakaoCallback.tsx
  frontend/src/pages/PU/components/form/EmailInput.tsx
  frontend/src/pages/PU/components/form/PasswordInput.tsx
  frontend/src/pages/PU/components/layout/Wrapper.tsx
  frontend/src/pages/PU/components/ui/Button.tsx
  frontend/src/stores/authStore.ts
  frontend/src/utils/handleToken.ts
Labels: feat

#123 fix: 댓글 작성/삭제 후 전체 페이지 새로고침으로 데이터 동기화
  frontend/src/pages/PN/PN-003/hooks/useComments.ts
Labels: fix

#128 feat: 비밀번호 재설정/변경 페이지 추가
  frontend/src/App.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/Sidebar.tsx
  frontend/src/components/ui/Button.tsx
  frontend/src/constants/PU/resetPasswordMessage.ts
  frontend/src/constants/url.ts
  frontend/src/pages/PN/PN-002/index.tsx
  frontend/src/pages/PN/PN-003/hooks/useTimelineData.ts
  frontend/src/pages/PN/PN-003/index.tsx
  frontend/src/pages/PU/PU-001/SignUpLogic.ts
  frontend/src/pages/PU/PU-002-01/useFindPasswordLogic.ts
  frontend/src/pages/PU/PU-002-02/ResetPasswordForm.tsx
  frontend/src/pages/PU/PU-002-02/index.tsx
  frontend/src/pages/PU/PU-002-02/useResetPasswordLogic.ts
  frontend/src/pages/PU/PU-002/useLoginLogic.ts
  frontend/src/pages/PU/PU-003/UserInfoForm.tsx
  frontend/src/pages/PU/PU-003/UserInfoLogic.ts
  frontend/src/pages/PU/auth/KakaoCallback.tsx
  frontend/src/pages/PU/components/form/PasswordCheckInput.tsx
  frontend/src/pages/PU/components/ui/Button.tsx
  frontend/src/pages/PU/utils/validateResetPassword.ts
  frontend/src/routes/LoginRoute.tsx
  frontend/src/routes/LogoutRoute.tsx
  frontend/src/routes/ResetPasswordRoute.tsx
  frontend/src/stores/useAuthStore.ts
  frontend/src/stores/usePageStore.ts
  frontend/src/stores/useRequestStore.ts
  frontend/src/stores/useSidebarStore.ts
Labels: feat

#119 fix: 회원정보 수정 페이지 수정
  frontend/src/constants/PU/userInfoMessage.ts
  frontend/src/pages/PU/PU-003/UserInfoForm.tsx
  frontend/src/pages/PU/PU-003/index.tsx
  frontend/src/pages/PU/PU-003/useUserInfoLogic.ts
  frontend/src/pages/PU/components/form/NicknameInput.tsx
Labels: fix, refactor

#132 feat: 투표 페이지(PV-001) 추가
  frontend/src/components/layout/AppContent.tsx
  frontend/src/components/layout/SidebarMenu/LoginMenu.tsx
  frontend/src/components/layout/Wrapper.tsx
  frontend/src/constants/PV/pollMessage.ts
  frontend/src/constants/url.ts
  frontend/src/pages/PU/PU-001/index.tsx
  frontend/src/pages/PU/PU-002-01/index.tsx
  frontend/src/pages/PU/PU-002-02/index.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/index.tsx
  frontend/src/pages/PV/PV-001/PollForm.tsx
  frontend/src/pages/PV/PV-001/PollOptionsForm.tsx
  frontend/src/pages/PV/PV-001/index.tsx
  frontend/src/pages/PV/PV-001/usePollLogic.ts
  frontend/src/pages/PV/components/Button.tsx
  frontend/src/pages/PV/utils/getFormatDateTime.ts
  frontend/src/routes/LoginRoute.tsx
  frontend/src/routes/LogoutRoute.tsx
  frontend/tailwind.config.js
Labels: feat

#134 release: 2.2.1 빌드 오류 해결
  frontend/.vite/deps/_metadata.json
  frontend/.vite/deps/package.json
Labels: fix, release

#135 release: 2.2.2 불필요한 모듈 삭제하여 빌드 오류 해결
  frontend/src/pages/PV/PV-001/PollOptionsForm.tsx
Labels: fix, release

#164 refactor: 검색 결과 페이지 컴포넌트 및 훅 분리
  frontend/src/App.css
  frontend/src/components/layout/Container.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/constants/PN/SearchResultMessage.ts
  frontend/src/constants/url.ts
  frontend/src/pages/PN/PN-001/NewsList.tsx
  frontend/src/pages/PN/PN-002/CreateNewsBtnBox.tsx
  frontend/src/pages/PN/PN-002/NewsList.tsx
  frontend/src/pages/PN/PN-002/index.tsx
  frontend/src/pages/PN/PN-002/useCreateNewsBtnName.ts
  frontend/src/pages/PN/PN-002/useSearchResultLogic.tsx
  frontend/src/pages/PN/PN-003/CommentSection.tsx
  frontend/src/pages/PN/PN-003/TimelineHeader.tsx
  frontend/src/pages/PN/components/layout/NewsCard.tsx
  frontend/src/pages/PN/components/layout/NewsCardListBox.tsx
  frontend/src/pages/PN/components/ui/Button.tsx
  frontend/src/pages/PN/types/news.ts
  frontend/src/pages/PN/utils/dateUtils.ts
  frontend/src/pages/PN/utils/formatRelativeTime.ts
  frontend/src/pages/PU/PU-001/index.tsx
  frontend/tailwind.config.js
Labels: feat, refactor

#170 feat: 뉴스 생성 로직 개선 및 뉴스 카드 UI 기능 통합 적용
  frontend/src/App.css
  frontend/src/constants/PN/SearchResultMessage.ts
  frontend/src/constants/url.ts
  frontend/src/lib/axios.ts
  frontend/src/pages/PN/PN-001/index.tsx
  frontend/src/pages/PN/PN-002/index.tsx
  frontend/src/pages/PN/PN-002/useSearchResultLogic.tsx
  frontend/src/pages/PN/components/layout/NewsCard.tsx
  frontend/src/pages/PN/components/layout/NewsCardListBox.tsx
  frontend/src/pages/PU/PU-001/index.tsx
  frontend/src/pages/PU/PU-002-01/index.tsx
  frontend/src/pages/PU/PU-002-02/index.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/index.tsx
  frontend/src/pages/PV/PV-001/index.tsx
  frontend/tailwind.config.js
Labels: feat, refactor

#175 refactor: 메인 페이지 리팩토링
  frontend/src/constants/PN/MainMessage.ts
  frontend/src/index.css
  frontend/src/pages/PN/PN-001/Banner.tsx
  frontend/src/pages/PN/PN-001/Carousel.tsx
  frontend/src/pages/PN/PN-001/Category.tsx
  frontend/src/pages/PN/PN-001/CategoryListBox.tsx
  frontend/src/pages/PN/PN-001/NewsList.tsx
  frontend/src/pages/PN/PN-001/index.tsx
  frontend/src/pages/PN/PN-001/useFetchHotissue.ts
  frontend/src/pages/PN/PN-001/useFetchNormal.ts
  frontend/src/pages/PN/PN-002/useSearchResultLogic.tsx
  frontend/src/pages/PN/components/layout/NewsCard.tsx
  frontend/src/pages/PN/types/category.ts
  frontend/src/pages/PN/types/news.ts
  frontend/tailwind.config.js
Labels: refactor

#176 release: v2.2.3 검색 결과 페이지, 메인 페이지 리팩토링
  .github/workflows/dev-frontend.yml
  frontend/src/App.css
  frontend/src/components/layout/Container.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/SidebarAlarm/AlarmCard.tsx
  frontend/src/constants/PN/MainMessage.ts
  frontend/src/constants/PN/SearchResultMessage.ts
  frontend/src/constants/url.ts
  frontend/src/index.css
  frontend/src/lib/axios.ts
  frontend/src/pages/PN/PN-001/Banner.tsx
  frontend/src/pages/PN/PN-001/Carousel.tsx
  frontend/src/pages/PN/PN-001/Category.tsx
  frontend/src/pages/PN/PN-001/CategoryListBox.tsx
  frontend/src/pages/PN/PN-001/NewsList.tsx
  frontend/src/pages/PN/PN-001/index.tsx
  frontend/src/pages/PN/PN-001/useFetchHotissue.ts
  frontend/src/pages/PN/PN-001/useFetchNormal.ts
  frontend/src/pages/PN/PN-002/CreateNewsBtnBox.tsx
  frontend/src/pages/PN/PN-002/NewsList.tsx
  frontend/src/pages/PN/PN-002/index.tsx
  frontend/src/pages/PN/PN-002/useCreateNewsBtnName.ts
  frontend/src/pages/PN/PN-002/useSearchResultLogic.tsx
  frontend/src/pages/PN/PN-003/CommentSection.tsx
  frontend/src/pages/PN/PN-003/TimelineHeader.tsx
  frontend/src/pages/PN/components/layout/NewsCard.tsx
  frontend/src/pages/PN/components/layout/NewsCardListBox.tsx
  frontend/src/pages/PN/components/ui/Button.tsx
  frontend/src/pages/PN/types/category.ts
  frontend/src/pages/PN/types/news.ts
  frontend/src/pages/PN/utils/dateUtils.ts
  frontend/src/pages/PN/utils/formatRelativeTime.ts
  frontend/src/pages/PU/PU-001/index.tsx
  frontend/src/pages/PU/PU-002-01/index.tsx
  frontend/src/pages/PU/PU-002-02/index.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/index.tsx
  frontend/src/pages/PV/PV-001/index.tsx
  frontend/tailwind.config.js
Labels: refactor, release

#178 feat: 자체 로그인 관련 페이지 및 내비게이션 링크 주석 처리
  frontend/src/components/layout/AppContent.tsx
  frontend/src/components/layout/SidebarMenu/LogoutMenu.tsx
  frontend/src/components/layout/SidebarMenu/SidebarMenu.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/UserInfoForm.tsx
Labels: feat

#180 feat: 불필요한 자체 로그인 관련 페이지 및 내비게이션 링크 주석 처리
  frontend/src/components/layout/AppContent.tsx
  frontend/src/components/layout/SidebarMenu/LogoutMenu.tsx
  frontend/src/components/layout/SidebarMenu/SidebarMenu.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/UserInfoForm.tsx
Labels: feat

#184 release: v2.4.0 북마크 페이지 추가
  frontend/src/components/layout/AppContent.tsx
  frontend/src/components/layout/SidebarMenu/LoginMenu.tsx
  frontend/src/components/layout/SidebarMenu/SidebarMenu.tsx
  frontend/src/constants/PN/BookmarkMessage.ts
  frontend/src/constants/url.ts
  frontend/src/pages/PN/PN-004/BookmarkTitleBox.tsx
  frontend/src/pages/PN/PN-004/index.tsx
  frontend/src/pages/PN/PN-004/useBookmarkLogic.ts
  frontend/tailwind.config.js
Labels: feat, release

#187 feat: 로그인 페이지 레이아웃 재구성 및 검색창 컴포넌트 아이콘에 색상 적용
  frontend/index.html
  frontend/src/assets/kakao_login_large_wide.png
  frontend/src/assets/tamnara_icon.png
  frontend/src/assets/tamnarna_icon.png
  frontend/src/components/layout/AppContent.tsx
  frontend/src/components/layout/SearchBar/SearchBar.tsx
  frontend/src/components/layout/SearchBar/SearchBox.tsx
  frontend/src/components/layout/SidebarMenu/LogoutMenu.tsx
  frontend/src/constants/PU/loginMessage.ts
  frontend/src/constants/PU/puMessage.ts
  frontend/src/pages/PU/PU-001/index.tsx
  frontend/src/pages/PU/PU-002/LoginNotice.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/UserInfoForm.tsx
  frontend/src/pages/PU/components/ui/Button.tsx
  frontend/src/pages/PU/components/ui/KakaoButton.tsx
  frontend/tailwind.config.js
Labels: feat

#195 refactor: 뉴스 상세 페이지(PN-003) 리팩토링
  frontend/src/components/ui/Button.tsx
  frontend/src/constants/PN/TimelineMessage.ts
  frontend/src/constants/url.ts
  frontend/src/pages/PN/PN-003/Comment/CommentCard.tsx
  frontend/src/pages/PN/PN-003/Comment/CommentContainer.tsx
  frontend/src/pages/PN/PN-003/Comment/CommentInput.tsx
  frontend/src/pages/PN/PN-003/Comment/MockComment.ts
  frontend/src/pages/PN/PN-003/CommentSection.tsx
  frontend/src/pages/PN/PN-003/SentimentAnalysis.tsx
  frontend/src/pages/PN/PN-003/Thumbnail.tsx
  frontend/src/pages/PN/PN-003/Timeline/TimelineCard.tsx
  frontend/src/pages/PN/PN-003/Timeline/TimelineContainer.tsx
  frontend/src/pages/PN/PN-003/TimelineCard.tsx
  frontend/src/pages/PN/PN-003/TimelineContainer.tsx
  frontend/src/pages/PN/PN-003/TimelineHeader.tsx
  frontend/src/pages/PN/PN-003/UpdateButtonBox.tsx
  frontend/src/pages/PN/PN-003/hooks/useComments.ts
  frontend/src/pages/PN/PN-003/hooks/useTimelineData.ts
  frontend/src/pages/PN/PN-003/hooks/useTypingText.ts
  frontend/src/pages/PN/PN-003/hooks/useUpdateNewsBtnName.ts
  frontend/src/pages/PN/PN-003/index.tsx
  frontend/src/pages/PN/PN-003/types.ts
  frontend/src/pages/PN/types/category.ts
  frontend/src/pages/PN/types/comment.ts
  frontend/src/pages/PN/types/news.ts
  frontend/src/pages/PN/types/newsDetail.ts
  frontend/src/pages/PN/types/statistics.ts
  frontend/src/pages/PN/types/timelineCard.ts
  frontend/src/pages/PN/utils/checkUpdateAvailable.ts
  frontend/src/stores/useAuthStore.ts
  frontend/src/utils/handleToken.ts
  frontend/tailwind.config.js
Labels: refactor

#199 feat: 메인 페이지에 무한 스크롤링 적용 및 뉴스 상세 페이지 댓글 로직 보완
  frontend/src/App.tsx
  frontend/src/components/layout/SidebarMenu/LoginMenu.tsx
  frontend/src/constants/url.ts
  frontend/src/pages/PN/PN-001/Carousel.tsx
  frontend/src/pages/PN/PN-001/Category.tsx
  frontend/src/pages/PN/PN-001/CategoryListBox.tsx
  frontend/src/pages/PN/PN-001/hooks/useFetchHotissue.ts
  frontend/src/pages/PN/PN-001/hooks/useFetchNormal.ts
  frontend/src/pages/PN/PN-001/index.tsx
  frontend/src/pages/PN/PN-001/useFetchNormal.ts
  frontend/src/pages/PN/PN-003/Comment/CommentContainer.tsx
  frontend/src/pages/PN/PN-003/UpdateButtonBox.tsx
  frontend/src/pages/PN/PN-003/index.tsx
  frontend/src/pages/PU/PU-002/LoginNotice.tsx
  frontend/src/pages/PU/PU-003/useUserInfoLogic.ts
  frontend/src/pages/PV/PV-001/usePollLogic.ts
  frontend/src/utils/handleToken.ts
Labels: feat

#204 feat: 검색 결과 페이지에 무한 스크롤링 적용
  frontend/src/components/layout/SidebarAlarm/AlarmCard.tsx
  frontend/src/constants/url.ts
  frontend/src/pages/PN/PN-001/hooks/useFetchNormal.ts
  frontend/src/pages/PN/PN-002/index.tsx
  frontend/src/pages/PN/PN-002/useSearchResultLogic.tsx
  frontend/src/pages/PN/PN-003/hooks/useToast.ts
Labels: feat

#207 refactor: 쿠키 기반 인증 방식으로 리팩토링
  frontend/src/App.tsx
  frontend/src/components/layout/SidebarMenu/LoginMenu.tsx
  frontend/src/components/layout/SidebarMenu/LogoutMenu.tsx
  frontend/src/components/ui/MenuButton.tsx
  frontend/src/constants/url.ts
  frontend/src/lib/axios.ts
  frontend/src/pages/PL/index.tsx
  frontend/src/pages/PN/PN-003/Comment/MockComment.ts
  frontend/src/pages/PN/PN-003/hooks/useComments.ts
  frontend/src/pages/PN/PN-003/index.tsx
  frontend/src/pages/PN/types/comment.ts
  frontend/src/pages/PU/PU-003/UserInfoForm.tsx
  frontend/src/pages/PU/PU-003/useUserInfoLogic.ts
  frontend/src/pages/PU/auth/KakaoCallback.tsx
  frontend/src/pages/PU/components/ui/StaticField.tsx
  frontend/src/pages/PV/PV-001/usePollLogic.ts
  frontend/src/stores/useAuthStore.ts
  frontend/src/utils/handleToken.ts
  frontend/tailwind.config.js
Labels: chore, refactor

#222 feat: Date/DateTime 상대적 시간 계산 유틸 함수 리팩토링, 투표 여부에 따른 투표 폼 비활성 분기 처리 추가, 로딩 페이지 추가
  frontend/src/components/layout/SidebarAlarm/SidebarAlarm.tsx
  frontend/src/constants/PL/LoadingMessage.ts
  frontend/src/constants/PV/pollMessage.ts
  frontend/src/pages/PL/LoadingContainer.tsx
  frontend/src/pages/PL/index.tsx
  frontend/src/pages/PL/useTypingLoadingText.ts
  frontend/src/pages/PN/PN-003/Comment/CommentCard.tsx
  frontend/src/pages/PN/PN-003/TimelineHeader.tsx
  frontend/src/pages/PN/components/layout/NewsCard.tsx
  frontend/src/pages/PV/PV-001/PollForm.tsx
  frontend/src/pages/PV/PV-001/PollOptionsForm.tsx
  frontend/src/pages/PV/PV-001/index.tsx
  frontend/src/pages/PV/PV-001/usePollLogic.ts
  frontend/src/utils/getRelativeDate.ts
  frontend/src/utils/getRelativeDateTime.ts
  frontend/tailwind.config.js
Labels: feat, refactor
