Repository 100-hours-a-week/18-team-timeline-fe, pull requests merged in 2025-05, with the labels that each got.

#7 feat: 프로젝트 초기 설정 및 공통 컴포넌트 구현
  frontend/.env
  frontend/.eslintrc
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/components/layout/Container.tsx
  frontend/src/components/layout/Header.tsx
  frontend/src/components/layout/Sidebar.tsx
  frontend/src/components/ui/Button.tsx
  frontend/src/components/ui/Icon.tsx
  frontend/src/components/ui/Modal.tsx
  frontend/src/components/ui/Text.tsx
  frontend/src/components/ui/Toast.tsx
  frontend/src/constants/url.ts
  frontend/src/index.css
  frontend/src/lib/axios.ts
  frontend/src/main.tsx
  frontend/src/pages/PN-001/index.tsx
  frontend/src/pages/PN-002/index.tsx
  frontend/src/pages/PU-001/index.tsx
  frontend/src/pages/PU-002/index.tsx
  frontend/src/pages/PU-003/index.tsx
  frontend/src/stores/authStore.ts
  frontend/src/stores/pageStore.ts
  frontend/src/stores/requestStore.ts
  frontend/src/stores/sidebarStore.ts
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
Labels: chore, feat

#10 feat: 로그인 페이지 구현
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/components/form/Input.tsx
  frontend/src/components/layout/Sidebar.tsx
  frontend/src/components/ui/Modal.tsx
  frontend/src/components/ui/Text.tsx
  frontend/src/components/ui/Toast.tsx
  frontend/src/constants/url.ts
  frontend/src/pages/PN/PN-001/index.tsx
  frontend/src/pages/PN/PN-002/index.tsx
  frontend/src/pages/PU-002/index.tsx
  frontend/src/pages/PU/PU-001/index.tsx
  frontend/src/pages/PU/PU-002/LoginForm.tsx
  frontend/src/pages/PU/PU-002/index.tsx
  frontend/src/pages/PU/PU-003/index.tsx
  frontend/src/pages/PU/components/layout/Wrapper.tsx
  frontend/src/pages/PU/components/ui/Button.tsx
  frontend/src/pages/PU/utils/validateLogin.ts
  frontend/tailwind.config.js
Labels: feat

#17 fix: 카카오 소셜 로그인 로직 수정
  frontend/.env
  frontend/src/App.tsx
  frontend/src/components/layout/Sidebar.tsx
  frontend/src/components/ui/Button.tsx
  frontend/src/pages/PU/auth/KakaoCallback.tsx
  frontend/src/pages/PU/components/ui/Button.tsx
  frontend/src/stores/authStore.ts
  frontend/src/utils/handleToken.ts
Labels: fix

#19 fix: 카카오 소셜 로그인 관련 API 연동 문제 해결
  frontend/src/components/ui/Button.tsx
  frontend/src/lib/axios.ts
  frontend/src/pages/PU/auth/KakaoCallback.tsx
  frontend/src/utils/handleToken.ts
Labels: critical bug, feat, fix

#36 feat: 로그인 상태에 따른 라우팅 접근 제한 설정
  frontend/src/App.tsx
  frontend/src/routes/LoginRoute.tsx
  frontend/src/routes/LogoutRoute.tsx
Labels: feat

#37 fix: 닉네임 유효성 검사 추가 및 체크박스 컴포넌트 라벨 색상 명시적으로 지정
  frontend/src/pages/PU/components/ui/CheckBox.tsx
  frontend/src/pages/PU/utils/validateSignUp.ts
  frontend/tailwind.config.js
Labels: fix, normal bug

#44 chore: 상세페이지 UI 개선
  frontend/src/pages/PN/PN-003/TimelineCard.tsx
  frontend/src/pages/PN/PN-003/TimelineHeader.tsx
  frontend/src/pages/PN/PN-003/hooks/useTimelineData.ts
  frontend/src/pages/PN/PN-003/index.tsx
  frontend/src/pages/PN/utils/dateUtils.ts
Labels: chore

#45 chore: 메인페이지 UI 개선
  frontend/src/pages/PN/PN-001/NewsList.tsx
Labels: chore

#47 chore: 텍스트 색상 명시
  frontend/src/pages/PN/PN-001/NewsList.tsx
  frontend/src/pages/PN/PN-003/SentimentAnalysis.tsx
  frontend/src/pages/PN/PN-003/TimelineCard.tsx
  frontend/src/pages/PN/PN-003/TimelineHeader.tsx
Labels: chore

#48 fix: 타임 포맷 개선
  frontend/src/pages/PN/utils/dateUtils.ts
Labels: fix

#52 refactor: 타임라인 카드 제목 잘리지 않게 하기
  frontend/src/pages/PN/PN-003/TimelineCard.tsx
Labels: chore

#59 [풀스택] [style] 누락된 Tailwind 클래스 추가 및 클래스명 변경사항 반영
  frontend/src/components/form/Input.tsx
  frontend/src/pages/PU/components/ui/StaticField.tsx
Labels: style

#66 feat: AI에서 에러를 반환했을 때 프론트 단의 처리
  frontend/src/pages/PN/PN-003/hooks/useTimelineData.ts
Labels: feat
